-- Add up migration script here
CREATE TABLE post  (
    id SERIAL PRIMARY KEY,
    tags JSONB NOT NULL,
    title VARCHAR(255) NOT NULL,
    first_publish TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_modify TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    count INTEGER NOT NULL DEFAULT 0
);